"""created matches table and updated comparision and submissions table

Revision ID: 5a77fef84992
Revises: 6709021a964a
Create Date: 2025-01-19 13:36:11.979119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a77fef84992'
down_revision: Union[str, None] = '6709021a964a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparisons', sa.Column('reviewer_id', sa.String(length=20), nullable=True))
    op.add_column('comparisons', sa.Column('reviewer_weightage', sa.Float(), nullable=True))
    op.add_column('comparisons', sa.Column('match_round', sa.Integer(), nullable=False))
    op.execute('UPDATE comparisons SET match_round = 1')
    op.alter_column('comparisons', 'submission_1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comparisons', 'submission_2_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('comparisons', 'comparison_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('comparisons', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'comparisons', 'teams', ['reviewer_id'], ['team_id'])
    op.add_column('submissions', sa.Column('match_round', sa.Integer(), nullable=False))
    op.alter_column('submissions', 'team_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('submissions', 'prompt',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('submissions', 'response',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('submissions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('submissions', 'table_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('submissions', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_team_round', 'submissions', ['team_id', 'match_round'], unique=False)
    op.create_index(op.f('ix_submissions_submission_id'), 'submissions', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_submission_id'), table_name='submissions')
    op.drop_index('idx_team_round', table_name='submissions')
    op.alter_column('submissions', 'submitted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('submissions', 'table_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('submissions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('submissions', 'response',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('submissions', 'prompt',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('submissions', 'team_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('submissions', 'match_round')
    op.drop_constraint(None, 'comparisons', type_='foreignkey')
    op.alter_column('comparisons', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('comparisons', 'comparison_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('comparisons', 'submission_2_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comparisons', 'submission_1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('comparisons', 'match_round')
    op.drop_column('comparisons', 'reviewer_weightage')
    op.drop_column('comparisons', 'reviewer_id')
    # ### end Alembic commands ###
