"""Create initial tables

Revision ID: 6709021a964a
Revises: 
Create Date: 2025-01-10 14:30:24.870928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6709021a964a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('team_id', sa.String(length=20), nullable=False),
    sa.Column('team_name', sa.String(length=20), nullable=False),
    sa.Column('team_full_name', sa.String(length=100), nullable=True),
    sa.Column('team_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('table_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('team_id'),
    sa.UniqueConstraint('team_name')
    )
    op.create_table('leaderboard',
    sa.Column('team_id', sa.String(length=20), nullable=False),
    sa.Column('elo_score', sa.BigInteger(), nullable=True),
    sa.Column('elo_rank', sa.Integer(), nullable=True),
    sa.Column('comparisons_made', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('last_match_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('submissions',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=20), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('table_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('comparisons',
    sa.Column('comparison_id', sa.Integer(), nullable=False),
    sa.Column('submission_1_id', sa.Integer(), nullable=True),
    sa.Column('submission_2_id', sa.Integer(), nullable=True),
    sa.Column('winner_submission_id', sa.Integer(), nullable=True),
    sa.Column('loser_submission_id', sa.Integer(), nullable=True),
    sa.Column('score_difference', sa.Integer(), nullable=True),
    sa.Column('comparison_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("comparison_status IN ('pending', 'completed', 'disputed')", name='valid_status'),
    sa.CheckConstraint('submission_1_id != submission_2_id', name='different_submissions'),
    sa.ForeignKeyConstraint(['loser_submission_id'], ['submissions.submission_id'], ),
    sa.ForeignKeyConstraint(['submission_1_id'], ['submissions.submission_id'], ),
    sa.ForeignKeyConstraint(['submission_2_id'], ['submissions.submission_id'], ),
    sa.ForeignKeyConstraint(['winner_submission_id'], ['submissions.submission_id'], ),
    sa.PrimaryKeyConstraint('comparison_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comparisons')
    op.drop_table('submissions')
    op.drop_table('leaderboard')
    op.drop_table('teams')
    # ### end Alembic commands ###
