"""Today morning

Revision ID: 69342120520e
Revises: fc0022addadd
Create Date: 2025-01-22 07:53:42.488017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69342120520e'
down_revision: Union[str, None] = 'fc0022addadd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team1_id', sa.String(length=20), nullable=False),
    sa.Column('team2_id', sa.String(length=20), nullable=False),
    sa.Column('match_round', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('match_round >= 0', name='valid_match_round'),
    sa.CheckConstraint('team1_id != team2_id', name='different_teams'),
    sa.ForeignKeyConstraint(['team1_id'], ['teams.team_id'], ),
    sa.ForeignKeyConstraint(['team2_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('match_id'),
    sa.UniqueConstraint('team1_id', 'team2_id', 'match_round', name='unique_match_combination')
    )
    op.drop_column('leaderboard', 'elo_rank')
    op.drop_column('leaderboard', 'last_match_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaderboard', sa.Column('last_match_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('elo_rank', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('matches')
    # ### end Alembic commands ###
