"""Latest database update

Revision ID: fc0022addadd
Revises: 5a77fef84992
Create Date: 2025-01-20 00:32:21.890566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0022addadd'
down_revision: Union[str, None] = '5a77fef84992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparisons', sa.Column('winner_team_id', sa.String(length=20), nullable=True))
    op.add_column('comparisons', sa.Column('loser_team_id', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'comparisons', 'teams', ['winner_team_id'], ['team_id'])
    op.create_foreign_key(None, 'comparisons', 'teams', ['loser_team_id'], ['team_id'])
    # op.create_unique_constraint('unique_match_combination', 'matches', ['team1_id', 'team2_id', 'match_round'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_match_combination', 'matches', type_='unique')
    op.drop_constraint(None, 'comparisons', type_='foreignkey')
    op.drop_constraint(None, 'comparisons', type_='foreignkey')
    op.drop_column('comparisons', 'loser_team_id')
    op.drop_column('comparisons', 'winner_team_id')
    # ### end Alembic commands ###
